apiVersion: v1
kind: Service
metadata:
  name: palworld-server
spec:
  selector:
    app.kubernetes.io/name: palworld
  ports:
    - protocol: TCP
      port: 8211
      targetPort: 8211
      nodePort: 30400
  type: NodePort
     